# Logistic Regression & ANN Models - Moriyah

In [1]:
import pandas as pd

df = pd.read_csv('/Users/morischick/Documents/CUNY/Spring 2021/Machine Learning/final project/NYPD_Complaint_All_Clean.csv', sep=",")


In [2]:
df.shape

(6817380, 22)

**Using data from 3 crime types for classification**

**1. Dangerous Drugs**

**2. Burglary**

**3. Intoxicated & Impaired Driving**


In [3]:
df = df.loc[df['OFNS_DESC'].isin(["DANGEROUS DRUGS", "BURGLARY", "INTOXICATED & IMPAIRED DRIVING"])]
df.head()

ADDR_PCT_CD CMPLNT_FR_DT CMPLNT_FR_TM   LAW_CAT_CD        OFNS_DESC  \
1         103.0   2015-05-28     06:40:00       FELONY         BURGLARY   
36         32.0   2015-05-28     21:45:00  MISDEMEANOR  DANGEROUS DRUGS   
57         62.0   2015-05-28     18:15:00  MISDEMEANOR  DANGEROUS DRUGS   
70         61.0   2015-05-28     20:30:00       FELONY         BURGLARY   
73         52.0   2015-05-28     21:09:00  MISDEMEANOR  DANGEROUS DRUGS   

   LOC_OF_OCCUR_DESC           JURIS_DESC   Latitude  Longitude NTACode  ...  \
1             INSIDE     N.Y. POLICE DEPT  40.705442 -73.807102    QN61  ...   
36       OPPOSITE OF  N.Y. HOUSING POLICE  40.825908 -73.937427    MN03  ...   
57               NaN     N.Y. POLICE DEPT  40.622604 -73.994295    BK28  ...   
70            INSIDE     N.Y. POLICE DEPT  40.586678 -73.920009    BK17  ...   
73          FRONT OF     N.Y. POLICE DEPT  40.864735 -73.905231    BX30  ...   

     sunrise    sunset               TIME_CAT   INSIDE TIME WEEK  DAY  \
1   05:29:28  20:17:29  MORNING AFTER SUNRISE   INSIDE    6   22   28   
36  05:29:28  20:17:29                  NIGHT  OUTSIDE   21   22   28   
57  05:29:28  20:17:29  EVENING BEFORE SUNSET  OUTSIDE   18   22   28   
70  05:29:28  20:17:29   EVENING AFTER SUNSET   INSIDE   20   22   28   
73  05:29:28  20:17:29                  NIGHT  OUTSIDE   21   22   28   

    DAY_OF_WEEK  WEEKEND  YEAR  
1             3  WEEKDAY  2015  
36            3  WEEKDAY  2015  
57            3  WEEKDAY  2015  
70            3  WEEKDAY  2015  
73            3  WEEKDAY  2015  

[5 rows x 22 columns]

In [4]:
df.shape

(728486, 22)

**Dimensionality Reduction**

Taking most informative attributes and discarding others

In [5]:
y=df['OFNS_DESC']
# X=df_knn[['ADDR_PCT_CD','Latitude','Longitude','YEAR','WEEK','DAY','DAY_OF_WEEK', 'TIME', 'TIME_CAT', 'INSIDE']]
# X=df_knn[['ADDR_PCT_CD','YEAR','WEEK','DAY','DAY_OF_WEEK', 'TIME', 'TIME_CAT', 'INSIDE']]

X=df[['WEEK','DAY','DAY_OF_WEEK', 'TIME', 'TIME_CAT', 'INSIDE']]
X_ready = pd.get_dummies(X, columns=['WEEK','DAY','DAY_OF_WEEK', 'TIME', 'TIME_CAT', 'INSIDE'])

In [6]:
X.shape

(728486, 6)

**Scaling the data for use in logistic regression and MLP models**

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_ready)
std_data = scaler.transform(X_ready)

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(std_data, y, test_size=0.2, random_state=0)

**Hyperparameter Tuning for MLP Model**

First attribute will be hidden layer size

**Hidden Layer Sizes= (1,)**

In [9]:
from sklearn.neural_network import MLPClassifier

logistic_mlp = MLPClassifier(hidden_layer_sizes=(1,), solver= 'sgd', early_stopping= True,
                              activation= 'logistic', alpha= 0.01, learning_rate_init= 0.01)

logistic_mlp.fit(X_train, y_train)
logistic_mlp.predict(X_test)
logistic_score = logistic_mlp.score(X_test, y_test)
print("Logistic: ", logistic_score)

relu_mlp = MLPClassifier(hidden_layer_sizes=(1,), solver= 'sgd', early_stopping= True,
                              activation= 'relu', alpha= 0.01, learning_rate_init= 0.01)

relu_mlp.fit(X_train, y_train)
relu_mlp.predict(X_test)
relu_score = relu_mlp.score(X_test, y_test)
print("ReLu: ", relu_score)

tanh_mlp = MLPClassifier(hidden_layer_sizes=(1,), solver= 'sgd', early_stopping= True,
                              activation= 'tanh', alpha= 0.01, learning_rate_init= 0.01)

tanh_mlp.fit(X_train, y_train)
tanh_mlp.predict(X_test)
tanh_score = tanh_mlp.score(X_test, y_test)
print("Tanh: ", tanh_score)

Logistic:  0.7327897431673737
ReLu:  0.7599967055141457
Tanh:  0.7321033919477274


**Hidden Layer Sizes=(2,2)**

In [10]:
logistic_mlp = MLPClassifier(hidden_layer_sizes=(2,2), solver= 'sgd', early_stopping= True,
                              activation= 'logistic', alpha= 0.01, learning_rate_init= 0.01)

logistic_mlp.fit(X_train, y_train)
logistic_mlp.predict(X_test)
logistic_score = logistic_mlp.score(X_test, y_test)
print("Logistic: ", logistic_score)

relu_mlp = MLPClassifier(hidden_layer_sizes=(2,2), solver= 'sgd', early_stopping= True,
                              activation= 'relu', alpha= 0.01, learning_rate_init= 0.01)

relu_mlp.fit(X_train, y_train)
relu_mlp.predict(X_test)
relu_score = relu_mlp.score(X_test, y_test)
print("ReLu: ", relu_score)

tanh_mlp = MLPClassifier(hidden_layer_sizes=(2,2), solver= 'sgd', early_stopping= True,
                              activation= 'tanh', alpha= 0.01, learning_rate_init= 0.01)

tanh_mlp.fit(X_train, y_train)
tanh_mlp.predict(X_test)
tanh_score = tanh_mlp.score(X_test, y_test)
print("Tanh: ", tanh_score)

Logistic:  0.772666749028813
ReLu:  0.7713626817114854
Tanh:  0.7696742577111559


**Hidden Layer Sizes=(10,)**

In [11]:
logistic_mlp = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                              activation= 'logistic', alpha= 0.01, learning_rate_init= 0.01)

logistic_mlp.fit(X_train, y_train)
logistic_mlp.predict(X_test)
logistic_score = logistic_mlp.score(X_test, y_test)
print("Logistic: ", logistic_score)

relu_mlp = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                              activation= 'relu', alpha= 0.01, learning_rate_init= 0.01)

relu_mlp.fit(X_train, y_train)
relu_mlp.predict(X_test)
relu_score = relu_mlp.score(X_test, y_test)
print("ReLu: ", relu_score)

tanh_mlp = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                              activation= 'tanh', alpha= 0.01, learning_rate_init= 0.01)

tanh_mlp.fit(X_train, y_train)
tanh_mlp.predict(X_test)
tanh_score = tanh_mlp.score(X_test, y_test)
print("Tanh: ", tanh_score)

Logistic:  0.7742453568339991
ReLu:  0.7740874960534805
Tanh:  0.7735315515655671


**Hidden Layer Sizes= (50,)**

In [12]:
from sklearn.neural_network import MLPClassifier

logistic_mlp = MLPClassifier(hidden_layer_sizes=(50,), solver= 'sgd', early_stopping= True,
                              activation= 'logistic', alpha= 0.01, learning_rate_init= 0.01)

logistic_mlp.fit(X_train, y_train)
logistic_mlp.predict(X_test)
logistic_score = logistic_mlp.score(X_test, y_test)
print("Logistic: ", logistic_score)

relu_mlp = MLPClassifier(hidden_layer_sizes=(50,), solver= 'sgd', early_stopping= True,
                              activation= 'relu', alpha= 0.01, learning_rate_init= 0.01)

relu_mlp.fit(X_train, y_train)
relu_mlp.predict(X_test)
relu_score = relu_mlp.score(X_test, y_test)
print("ReLu: ", relu_score)

tanh_mlp = MLPClassifier(hidden_layer_sizes=(50,), solver= 'sgd', early_stopping= True,
                              activation= 'tanh', alpha= 0.01, learning_rate_init= 0.01)

tanh_mlp.fit(X_train, y_train)
tanh_mlp.predict(X_test)
tanh_score = tanh_mlp.score(X_test, y_test)
print("Tanh: ", tanh_score)

Logistic:  0.7743963541023212
ReLu:  0.7739364987851584
Tanh:  0.7735864596631388


Seems like hidden layer size doesn't make that much of a difference after a certain point so we'll keep hidden layer size at (10,) and check other parameters

**The next feature to be optimized is the initialized learning rate**

**Learning Rate Init=0.1**

In [13]:
logistic_mlp = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                              activation= 'logistic', alpha= 0.1, learning_rate_init= 0.1)

logistic_mlp.fit(X_train, y_train)
logistic_mlp.predict(X_test)
logistic_score = logistic_mlp.score(X_test, y_test)
print("Logistic: ", logistic_score)

relu_mlp = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                              activation= 'relu', alpha= 0.1, learning_rate_init= 0.1)

relu_mlp.fit(X_train, y_train)
relu_mlp.predict(X_test)
relu_score = relu_mlp.score(X_test, y_test)
print("ReLu: ", relu_score)

tanh_mlp = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                              activation= 'tanh', alpha= 0.1, learning_rate_init= 0.1)

tanh_mlp.fit(X_train, y_train)
tanh_mlp.predict(X_test)
tanh_score = tanh_mlp.score(X_test, y_test)
print("Tanh: ", tanh_score)

Logistic:  0.7720490329311315
ReLu:  0.771685266784719
Tanh:  0.7725157517604909


**Learning Rate Init=0.001**

In [14]:
logistic_mlp = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                              activation= 'logistic', alpha= 0.001, learning_rate_init= 0.001)

logistic_mlp.fit(X_train, y_train)
logistic_mlp.predict(X_test)
logistic_score = logistic_mlp.score(X_test, y_test)
print("Logistic: ", logistic_score)

relu_mlp = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                              activation= 'relu', alpha= 0.001, learning_rate_init= 0.001)

relu_mlp.fit(X_train, y_train)
relu_mlp.predict(X_test)
relu_score = relu_mlp.score(X_test, y_test)
print("ReLu: ", relu_score)

tanh_mlp = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                              activation= 'tanh', alpha= 0.001, learning_rate_init= 0.001)

tanh_mlp.fit(X_train, y_train)
tanh_mlp.predict(X_test)
tanh_score = tanh_mlp.score(X_test, y_test)
print("Tanh: ", tanh_score)

Logistic:  0.7737305934192645
ReLu:  0.773812955565622
Tanh:  0.7733874178094414


**MLP w/ LDA**

Create train and test sets transformed using LDA

Will use for both MLP and LR model later

In [15]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

X_train2, X_test2, y_train2, y_test2 = train_test_split(std_data, y, test_size=0.2, random_state=1)

lda = LDA()
X_train_lda = lda.fit_transform(X_train2, y_train2)
X_test_lda = lda.fit_transform(X_test2, y_test2)

In [16]:
# put MLP trained on LDA transformed data here

MLP_LDA = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                        activation= 'tanh', alpha= 0.01, learning_rate_init= 0.01)

MLP_LDA.fit(X_train_lda, y_train2)
MLP_LDA.predict(X_test_lda)
MLP_LDA_score = MLP_LDA.score(X_test_lda, y_test2)
print("MLP w/ LDA: ", MLP_LDA_score)

MLP w/ LDA:  0.7710538236626446


**The optimal MLP model found:**

Hidden Layer Size: (10,)

Activation Function: Tanh

Initialized Learning Rate: 0.01

In [17]:
best_MLP = MLPClassifier(hidden_layer_sizes=(10,), solver= 'sgd', early_stopping= True,
                        activation= 'tanh', alpha= 0.01, learning_rate_init= 0.01)
best_MLP.fit(X_train, y_train)
MLP_pred = best_MLP.predict(X_test)
print(best_MLP.score(X_test, y_test))

0.7739021812241761


**Cross Validation**

In [19]:
from sklearn.model_selection import cross_val_score
import numpy as np

MLP_cross_val_score = cross_val_score(best_MLP, X_train, y_train, scoring='accuracy', cv=5)

print("Mean of LR 5-Fold Cross Validation: ", np.mean(MLP_cross_val_score))

Mean of LR 5-Fold Cross Validation:  0.7733172226361138


In [20]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, classification_report
import numpy as np

accuracy_MLP = np.mean(MLP_pred == y_test)
print("\nBest MLP Accuracy: ", accuracy_MLP)


print("\nBest MLP Confusion Matrix:")
print(confusion_matrix(y_test, MLP_pred))


precision_MLP = precision_score(y_test, MLP_pred, average='micro') 
print("\nBest MLP Precision = %f" % precision_MLP)

recall_MLP = recall_score(y_test, MLP_pred, average='micro')
print("Best MLP Recall = %f" % recall_MLP)


f1_MLP = f1_score(y_test, MLP_pred, average='micro')
print("Best MLP F1 Score = %f" % f1_MLP)


print("\nClassification Report:")
print(classification_report(y_test, MLP_pred))


Best MLP Accuracy:  0.7739021812241761

Best MLP Confusion Matrix:
[[36341  7364   550]
 [11946 66102  4680]
 [  128  8274 10313]]

Best MLP Precision = 0.773902
Best MLP Recall = 0.773902
Best MLP F1 Score = 0.773902

Classification Report:
                                precision    recall  f1-score   support

                      BURGLARY       0.75      0.82      0.78     44255
               DANGEROUS DRUGS       0.81      0.80      0.80     82728
INTOXICATED & IMPAIRED DRIVING       0.66      0.55      0.60     18715

                      accuracy                           0.77    145698
                     macro avg       0.74      0.72      0.73    145698
                  weighted avg       0.77      0.77      0.77    145698



# Logistic Regression

Using the same dataset as above so data has aleady been scaled.

Hyperparameter tuning of regularization constant for logistic regression model:

(set by default to L2 regularization)

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

param_grid_ = {'C': [1e-5, 1e-3, 1e-1, 1e0, 1e1, 1e2]}
LR_search = GridSearchCV(LogisticRegression(verbose=10, multi_class='multinomial', solver='lbfgs'), cv=5, param_grid=param_grid_)

LR_search.fit(X_train, y_train)

params_optimal_LR = LR_search.best_params_

print(params_optimal_LR)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    7.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    7.6s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.9s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.9s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    6.8s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    9.7s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    9.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent work

{'C': 1.0}


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   16.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   16.8s finished


In [23]:
LR_pred = LR_search.predict(X_test)
LR_search.score(X_test, y_test)

0.7728108827849387

In [24]:
logreg = LogisticRegression(C=10, multi_class='multinomial', solver='lbfgs')
logreg.fit(X_train, y_train)
LR_pred = logreg.predict(X_test)
print(logreg.score(X_test, y_test))

0.7728108827849387


**Cross Validation**

In [25]:
LR_cross_val_score = cross_val_score(logreg, X_train, y_train, scoring='accuracy', cv=5)

print("Mean of LR 5-Fold Cross Validation: ", np.mean(LR_cross_val_score))

Mean of LR 5-Fold Cross Validation:  0.7725622306415109


**Logistic Regression w/ LDA**

In [26]:
LR_LDA = LogisticRegression(C=10).fit(X_train_lda, y_train2)
LR_LDA_score = LR_LDA.score(X_test_lda, y_test2)
print(LR_LDA_score)

0.7662905461983006


**Final Results of Optimized Logistic Regression Model**

In [27]:
accuracy_LR = np.mean(LR_pred == y_test)
print("\nTrain Accuracy: ", accuracy_LR)


print("\nTrain Confusion Matrix:")
print(confusion_matrix(y_test, LR_pred))


precision_test = precision_score(y_test, LR_pred, average='micro') 
print("\nTrain Precision = %f" % precision_test)

recall_test = recall_score(y_test, LR_pred, average='micro')
print("Test Recall = %f" % recall_test)


f1_test = f1_score(y_test, LR_pred, average='micro')
print("Test F1 Score = %f" % f1_test)


print("\nClassification Report:")
print(classification_report(y_test, LR_pred))


Train Accuracy:  0.7728108827849387

Train Confusion Matrix:
[[36580  7168   507]
 [12198 65904  4626]
 [  110  8492 10113]]

Train Precision = 0.772811
Test Recall = 0.772811
Test F1 Score = 0.772811

Classification Report:
                                precision    recall  f1-score   support

                      BURGLARY       0.75      0.83      0.79     44255
               DANGEROUS DRUGS       0.81      0.80      0.80     82728
INTOXICATED & IMPAIRED DRIVING       0.66      0.54      0.60     18715

                      accuracy                           0.77    145698
                     macro avg       0.74      0.72      0.73    145698
                  weighted avg       0.77      0.77      0.77    145698

